### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError

### ISSUE THREAD

**Issue by andreialecu** [nestjs/bull#192]
I've just came across this library and while trying to implement it I'm running into the followin error:

```
(node:17352) UnhandledPromiseRejectionWarning: TypeError
    at Object.getMetadata (\node_modules\reflect-metadata\Reflect.js:354:23)
    at Reflector.get (\node_modules\@nestjs\core\services\reflector.service.js:23:24)
    at BullMetadataAccessor.isQueueComponent (\node_modules\@nestjs\bull\dist\bull-metadata.accessor.js:23:33)
    at \node_modules\@nestjs\bull\dist\bull.explorer.js:38:56
    at Array.filter (<anonymous>)
    at BullExplorer.explore (\node_modules\@nestjs\bull\dist\bull.explorer.js:38:14)
    at BullModule.onModuleInit (\node_modules\@nestjs\bull\dist\bull.module.js:50:23)
    at Object.callModuleInitHook (\node_modules\@nestjs\core\hooks\on-module-init.hook.js:42:35)
    at async NestApplication.callInitHook (\node_modules\@nestjs\core\nest-application-context.js:140:13)
    at async NestApplication.init (\node_modules\@nestjs\core\nest-application.js:90:9)
    at async NestApplication.listen (\node_modules\@nestjs\core\nest-application.js:142:33)
```

The only thing I did was to add this:
```
@Module({
  imports: [
    BullModule.register({
      name: 'jobs',
      redis: {
        port: 6379,
      },
    }),
``` 
To my module declaration.

Any ideas?

@nestjs/core@6.10.11
@nestjs/bull@0.0.1-beta.1 (seems to be latest on npm)

**Comment by andreialecu** [comment]
I've installed `@next` which got me to `0.0.1-beta.3` instead and now the error is gone, but there's a different one:

`(node:32656) UnhandledPromiseRejectionWarning: Error: Nest could not find BullQueue_default element (this provider does not exist in the current context)`

Is this library not production ready?

**Comment by andreialecu** [comment]
Ok I got it, the problem was because my `@Processor()` decorator didn't have the name `@Processor('jobs')` in it, like the one used for registering the module in the first place.

Now the error is gone. Documentation seems to be severely lacking though. This error could be improved.

Also, in the readme it is said to use `options: { redis: ... }`, but `options` doesn't exist.

**Comment by kamilmysliwiec** [comment]
We are tracking the documentation here https://github.com/nestjs/docs.nestjs.com/pull/887
